version: "2"

linters:
  default: all

  disable:
    - depguard
    - paralleltest

  settings:
    cyclop:
      max-complexity: 20

    funlen:
      lines: 100
      ignore-comments: true

    revive:
      rules:
        - name: exported
          disabled: true

    varnamelen:
      ignore-decls:
        - i int
        - T any

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - err113
          - exhaustruct
