version: "2"

linters:
  default: all

  disable:
    - depguard
    - paralleltest

  settings:
    cyclop:
      max-complexity: 20

    revive:
      rules:
        - name: exported
          disabled: true
