// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockLogger
func (_mock *MockLogger) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogger_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLogger_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLogger_Expecter) Close() *MockLogger_Close_Call {
	return &MockLogger_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLogger_Close_Call) Run(run func()) *MockLogger_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_Close_Call) Return(err error) *MockLogger_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogger_Close_Call) RunAndReturn(run func() error) *MockLogger_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) Debug(msg interface{}, fields ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, fields ...slog.Attr)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, fields ...slog.Attr)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// DebugWithContext provides a mock function for the type MockLogger
func (_mock *MockLogger) DebugWithContext(ctx context.Context, msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_DebugWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugWithContext'
type MockLogger_DebugWithContext_Call struct {
	*mock.Call
}

// DebugWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) DebugWithContext(ctx interface{}, msg interface{}, fields ...interface{}) *MockLogger_DebugWithContext_Call {
	return &MockLogger_DebugWithContext_Call{Call: _e.mock.On("DebugWithContext",
		append([]interface{}{ctx, msg}, fields...)...)}
}

func (_c *MockLogger_DebugWithContext_Call) Run(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_DebugWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_DebugWithContext_Call) Return() *MockLogger_DebugWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_DebugWithContext_Call) RunAndReturn(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_DebugWithContext_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) Error(msg interface{}, fields ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, fields ...slog.Attr)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, fields ...slog.Attr)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorWithContext provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorWithContext(ctx context.Context, msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_ErrorWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorWithContext'
type MockLogger_ErrorWithContext_Call struct {
	*mock.Call
}

// ErrorWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) ErrorWithContext(ctx interface{}, msg interface{}, fields ...interface{}) *MockLogger_ErrorWithContext_Call {
	return &MockLogger_ErrorWithContext_Call{Call: _e.mock.On("ErrorWithContext",
		append([]interface{}{ctx, msg}, fields...)...)}
}

func (_c *MockLogger_ErrorWithContext_Call) Run(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_ErrorWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorWithContext_Call) Return() *MockLogger_ErrorWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorWithContext_Call) RunAndReturn(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_ErrorWithContext_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) Info(msg interface{}, fields ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, fields ...slog.Attr)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, fields ...slog.Attr)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// InfoWithContext provides a mock function for the type MockLogger
func (_mock *MockLogger) InfoWithContext(ctx context.Context, msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_InfoWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoWithContext'
type MockLogger_InfoWithContext_Call struct {
	*mock.Call
}

// InfoWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) InfoWithContext(ctx interface{}, msg interface{}, fields ...interface{}) *MockLogger_InfoWithContext_Call {
	return &MockLogger_InfoWithContext_Call{Call: _e.mock.On("InfoWithContext",
		append([]interface{}{ctx, msg}, fields...)...)}
}

func (_c *MockLogger_InfoWithContext_Call) Run(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_InfoWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_InfoWithContext_Call) Return() *MockLogger_InfoWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_InfoWithContext_Call) RunAndReturn(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_InfoWithContext_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) Warn(msg interface{}, fields ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, fields ...slog.Attr)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, fields ...slog.Attr)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// WarnWithContext provides a mock function for the type MockLogger
func (_mock *MockLogger) WarnWithContext(ctx context.Context, msg string, fields ...slog.Attr) {
	// slog.Attr
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockLogger_WarnWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnWithContext'
type MockLogger_WarnWithContext_Call struct {
	*mock.Call
}

// WarnWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - fields ...slog.Attr
func (_e *MockLogger_Expecter) WarnWithContext(ctx interface{}, msg interface{}, fields ...interface{}) *MockLogger_WarnWithContext_Call {
	return &MockLogger_WarnWithContext_Call{Call: _e.mock.On("WarnWithContext",
		append([]interface{}{ctx, msg}, fields...)...)}
}

func (_c *MockLogger_WarnWithContext_Call) Run(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_WarnWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		variadicArgs := make([]slog.Attr, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(slog.Attr)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_WarnWithContext_Call) Return() *MockLogger_WarnWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_WarnWithContext_Call) RunAndReturn(run func(ctx context.Context, msg string, fields ...slog.Attr)) *MockLogger_WarnWithContext_Call {
	_c.Run(run)
	return _c
}
